### ISSUE TITLE
The "config.decay" prop is undocumented

### ISSUE THREAD

**Issue by aleclarson** [react-spring/react-spring.io#11]
It should be added here: https://www.react-spring.io/docs/hooks/api

Reported here: https://github.com/react-spring/react-spring/issues/645#issuecomment-488942253

**Comment by thiskevinwang** [comment]
I just discovered `config.decay`!!! And this issue... 
- Discovered in https://github.com/react-spring/react-use-gesture#how-do-i-use-memo
