### ISSUE TITLE
Memory leak on examples page

### ISSUE THREAD

**Issue by aleclarson** [react-spring/react-spring.io#15]
Might be a react-spring leak 😳

- Goto https://www.react-spring.io/docs/hooks/examples
- Start heap profiler?
- Leave it open until it crashes?

**Comment by drcmda** [comment]
which section? they mount only when they're visible on screen, so that would already show you the ones that could cause it.

**Comment by DmacTorstar** [comment]
Confirmed that react-spring with SSR is causing a memory leak.

**Comment by DeviousM** [comment]
Absolutely confirmed that react-spring is causing a massive memory leak with SSR.
![image](https://user-images.githubusercontent.com/9259157/68210808-9f2b2580-ffd6-11e9-9516-665c225a6cfb.png)

**Comment by joshuaellis** [comment]
I think this was fixed in v9
