### ISSUE TITLE
Fix mobile layout

### ISSUE THREAD

**Issue by aleclarson** [react-spring/react-spring.io#17]
An attendee at React Europe showed me how react-spring.io looks on mobile, and it's kinda broken.

**Comment by vaibhavhrt** [comment]
@aleclarson Well it's works, but user can have a better experience. This will take a while so maybe I will do all components on one route at a time,  so expect multiple PRs(unless you guyz are ok with PR which change a lot of code). I will open a PR in the next few, most likely sometime next week.
