### ISSUE TITLE
Use react-live or similar for the examples

### ISSUE THREAD

**Issue by gfrancischelli** [react-spring/react-spring.io#18]
[`react-live`](https://github.com/FormidableLabs/react-live) is a `"production-focused playground for live editing React code"`.

It should simplify the existing workflow on updating examples and I think it also make more easy for people to play with them.

### Motivation

This week I've implemented a swipe-to-delete component with `react-spring` and it was kinda painful to learn since the [gesture slider example](https://codesandbox.io/embed/zrj66y8714) still uses the old `react-with-gesture` api instead of `react-use-gesture`.

Forking the repo to update the gesture examples I've felt like it is over-complicated to update the code and it is not clear how to update the codesandboxes.

If the idea is welcome I'm willing to propose and develop a new examples setup.

Any thoughts ?

**Comment by drcmda** [comment]
Its a good idea, theoretically the react-examples repo has all the parts needed to pull this off. Would you want to give it a go yourself?

**Comment by gfrancischelli** [comment]
I'm very happy to contribute with this 😁

Expect a PR to validate and iterate the design soon!

**Comment by drcmda** [comment]
Wow, nice! @aleclarson

**Comment by aleclarson** [comment]
Sounds like a plan! LMK if you hit any bumps along the way. 👍
