### ISSUE TITLE
Code sample text color is white on white

### ISSUE THREAD

**Issue by mxstbr** [react-spring/react-spring.io#19]
![Screenshot 2019-06-04 at 15 00 06](https://user-images.githubusercontent.com/7525670/58880975-76c29680-86d9-11e9-90c3-56d2da6e807c.png)

**Comment by drcmda** [comment]
dammit this is new ... all code blocks suddenly lost formatting :-S thanks for the heads up!

**Comment by aleclarson** [comment]
I'm not seeing this?
