### ISSUE TITLE
Add some guides

### ISSUE THREAD

**Issue by aleclarson** [react-spring/react-spring.io#20]
Everyone is encouraged to help out with these tasks:

- [ ] Add a "guide directory" page
- [ ] Write a short guide for getting started with each target platform (eg: web, zdog, three)
- [ ] Convert solved questions from https://github.com/react-spring/react-spring/issues into guided implementations
- [ ] Write a short guide about how you fixed a broken animation while learning `react-spring`

It would be great if the guides used [`react-live`](https://github.com/FormidableLabs/react-live)!

**Comment by bradwoods** [comment]
I've written a [list of examples](https://examples.bradwoods.io/react-spring) of react-spring concepts. I've tried to make each example with the minimum amount of code required. Putting a link to these examples somewhere in the docs may help some people.

**Comment by joshuaellis** [comment]
@bradwoods would you be interested in moving these to the `react-spring` repo and in turn they can then be utilised in `react-spring.io`? I've noticed they're using v8, so updating them would be good too? 😅

**Comment by bradwoods** [comment]
I think I'd rather keep them within the project their currently located in. I'll update them to the latest version sometime next week.
