### ISSUE TITLE
Document recommendations for building accessible animations

### ISSUE THREAD

**Issue by infiniteluke** [react-spring/react-spring.io#31]
In https://github.com/react-spring/react-spring/issues/811, a cross platform `useReduceMotion` hook was proposed. It was decided this would best live in user-land.

The original post on that issue outlines the importance encouraging devs to make accessible animations. Since making that proposal, I have shipped https://github.com/infiniteluke/react-reduce-motion, a cross platform solution for hooking into users' "Reduce motion" OS preference.

Documenting this approach and making a recommendation on the official react spring site is a good idea because it will provide visibility about the importance of accessibility and will empower devs to understand that it's not so hard to support!

Where should this live in the react-spring.io site? 

Here are a couple options:

## Option 1

![image](https://user-images.githubusercontent.com/1127238/66498005-394c8c00-ea72-11e9-944b-e5a1020e6e68.png)

This is nice because it is very visible and will remind people about accessibility from the start when learning about react-spring. This is my preference, but maybe I'm biased.. 😉

## Option 2

![image](https://user-images.githubusercontent.com/1127238/66498303-b415a700-ea72-11e9-9992-baa3a81ea434.png)

This option may be preferable if you all want the recommendation to be less prominent.

Once it is decided this is an acceptable idea and the location is determined. I can open a PR and we can discuss the verbiage.

Thanks!

**Comment by infiniteluke** [comment]
@aleclarson Can I get some feedback on this doc site change? I'm happy to open a PR with my preferences if that's preferred. Thanks!

**Comment by TheSisb** [comment]
+1 for Option A, for visibility.  The menu is pretty minimalist, so it fits nicely.
