### ISSUE TITLE
https://www.react-spring.io website is down

### ISSUE THREAD

**Issue by arjun-kava** [react-spring/react-spring.io#33]
Hello, guys
I am trying to find documentation but documentation website is down
accessing from Gujrat, India.

**Comment by mcernusca** [comment]
Hmm website is up but DNS settings seemingly got reset - unsure if intentional.

@arjun-kava use this link for now: https://dreamy-shaw-ac0e50.netlify.com

**Comment by mcernusca** [comment]
It’s back 🥳. Thanks for reporting @arjun-kava
