### ISSUE TITLE
Warnings and Contributing Guides

### ISSUE THREAD

**Issue by jordanliu** [react-spring/react-spring.io#39]
I started up a local instance of the docs and realized there are many errors and a lack of documentation for contribution, I'd love to contribute. 

Console:
![image](https://user-images.githubusercontent.com/9423525/85032233-32b7fd80-b145-11ea-8457-286668df7c25.png)

Can I take on this issue of cleaning up the warnings and adding a proper readme and contributing guide?

**Comment by jordanliu** [comment]
@mcernusca @aleclarson

**Comment by jordanliu** [comment]
bump: @mcernusca @aleclarson

**Comment by joshuaellis** [comment]
There's a new doc site being built on the `/docs` branch. It's the same visual style, just different architecture. You're welcome to submit a PR to that branch, otherwise I will do it 😄

**Comment by jordanliu** [comment]
@joshuaellis sounds good!
