### ISSUE TITLE
Where i can found the react-spring v8.** documentation (old react-spring.io)

### ISSUE THREAD

**Issue by anassboutaline** [react-spring/react-spring.io#55]
## 🤓 Question

I have a lot of packages depend on react spring 8.0.27, so i can't upgrade to v9.0.0, i'm wondering why you can't keep the old documentation accessible ex. react-spring.io/doc/v8 or somthing

**Comment by joshuaellis** [comment]
The docs infrastructure has been changed to nextjs and all the demos have been updated to v9. If you want to put in the work to do this change, I don’t think it’ll take you very long. The v9 update was just one squashed commit.

I should add development is frozen on v8.

**Comment by joshuaellis** [comment]
Update: I have made a branch for v8 so you can still access the `.md` files – https://github.com/pmndrs/react-spring.io/tree/8.0.0

However integrating into the site I will be leaving to contributors.

**Comment by anassboutaline** [comment]
Thank you for the branch, you saved me from a lot of work
