### ISSUE TITLE
Better documentation needed to migrate velocity props from v8 to v9

### ISSUE THREAD

**Issue by MattyBalaam** [react-spring/react-spring.io#62]
## 🐛 Bug Report

The Velocity prop has changed for v9 and the changelog does not mention it

## To Reproduce

A value of `1` in v8 will need to be changed to `0.001` in v9. 

## Expected behavior

This should be in this guide:  https://aleclarson.github.io/react-spring/v9/breaking-changes/

Change to library is here: https://github.com/pmndrs/react-spring/commit/d5ad40fb9f6dccdb7f28bd62b0a5455b1a6a74cf

**Comment by swashata** [comment]
@joshuaellis Coming from pmndrs/react-spring#1470 I can confirm multiplying v8 `velocity` with `0.001` retains the same behavior. I am thinking I can add the information here? https://github.com/pmndrs/react-spring.io/blob/master/src/pages/common/configs.mdx If so, please confirm and I will do it.

**Comment by joshuaellis** [comment]
So i'd add it to the [v9 changelog](https://github.com/pmndrs/react-spring.io/blob/master/src/pages/changelog.mdx). And then yeah where you're suggesting would be a good idea, i'd try do it in the same style as [this](https://github.com/pmndrs/react-spring.io/blob/master/src/pages/common/props.mdx) how if there's more information for an item we have a seperate heading, as not to clog up the tabl
