### ISSUE TITLE
Is onDestroyed meant to be deprecated in v9, if so - what replaces it?

### ISSUE THREAD

**Issue by MattyBalaam** [react-spring/react-spring.io#63]
## 🐛 Bug Report

I have read that `onDestroyed` has been removed in v9. https://aleclarson.github.io/react-spring/v9/breaking-changes/#The-sort-prop - however, the Typescript definitions still have it, and it fires callbacks.

- Should this have been removed, or is this prop missing in the new documentation?
- What is meant to be used instead on this prop if is being removed?

## To Reproduce

The prop is called here: https://github.com/pmndrs/react-spring/blob/9568020efb64addb97816232759528a7681ed97c/packages/core/src/hooks/useTransition.tsx#L110

## Environment

- `react-spring` v9.

**Comment by MattyBalaam** [comment]
I guess that makes the most sense, although it is partly a question around the codebase and the correct behaviour moving forward. It would be good to get clarification on the correct expectation for this prop if it is meant to be sticking around.

**Comment by joshuaellis** [comment]
I don't plan on removing it.
